CREATE TABLE [dbo].[EquityStage]
(
[Asset_Type] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[Name] [varchar] (450) COLLATE Latin1_General_CI_AS NOT NULL,
[DelistedDefunct] [bit] NULL,
[ListingDate] [datetime] NULL,
[ListingStatus] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusDate] [datetime] NULL,
[InstrumentStatusCreatedDatetime] [datetime] NULL,
[Sector] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Subfocus1] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Subfocus2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Subfocus3] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Subfocus4] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Subfocus5] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ApprovalType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ApprovalDate] [datetime] NULL,
[TdFlag] [bit] NULL,
[MadFlag] [bit] NULL,
[PdFlag] [bit] NULL,
[Gid] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[IssuerGid] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[Isin] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Sedol] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[IssuedDate] [datetime] NULL,
[MarketType] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SecurityType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DenominationCurrency] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ISEQOverallFreeFloat] [decimal] (23, 10) NULL,
[ISEQ20IndexFlag] [bit] NULL,
[ESMIndexFlag] [bit] NULL,
[IteqIndexFlag] [bit] NULL,
[GeneralFinancialFlag] [bit] NULL,
[SmallCap] [bit] NULL,
[Note] [varchar] (300) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[QuotationCurrency] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[UnitOfQuotation] [decimal] (23, 10) NULL,
[Wkn] [varchar] (6) COLLATE Latin1_General_CI_AS NULL,
[Mnem] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[CfiName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CfiCode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[SmfName] [varchar] (40) COLLATE Latin1_General_CI_AS NULL,
[TotalSharesInIssue] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[InstrumentActualListedDate] [datetime] NULL,
[TradingSysInstrumentName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CompanyGid] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ExDividend] [bit] NULL,
[ExCapitalisation] [bit] NULL,
[ExRights] [bit] NULL,
[ExSpecial] [bit] NULL,
[ExEntitlement] [bit] NULL,
[SecurityQualifier] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[ExDividendDate] [datetime] NULL,
[ExtractSequenceId] [bigint] NOT NULL IDENTITY(1, 1),
[ExtractDate] [datetime] NULL CONSTRAINT [DF__EquitySta__Extra__267ABA7A] DEFAULT (getdate()),
[MessageId] [varchar] (256) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EquityStage] ADD CONSTRAINT [PK__EquitySt__A1071C3D03252DAE] PRIMARY KEY CLUSTERED  ([ExtractSequenceId]) ON [PRIMARY]
GO
