CREATE TABLE [dbo].[CorporateActionStage]
(
[Gid] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[InstrumentGID] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[IssuerGID] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[CorpActionType] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[CorpActionAssetType] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[SpecialActionHeadline] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[AdditionalDescription] [varchar] (3000) COLLATE Latin1_General_CI_AS NULL,
[Conditional] [bit] NULL,
[CouponNumber] [decimal] (23, 10) NULL,
[Currency] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Details] [varchar] (3000) COLLATE Latin1_General_CI_AS NULL,
[DividendPerShare] [decimal] (23, 10) NULL,
[DividendRatePercent] [decimal] (23, 10) NULL,
[EffectiveDate] [datetime] NULL,
[ExDate] [datetime] NULL,
[ExPrice] [decimal] (23, 10) NULL,
[FXRate] [decimal] (23, 10) NULL,
[GrossDividendEuro] [decimal] (23, 10) NULL,
[GrossDividend] [decimal] (23, 10) NULL,
[LatestDateForApplicationNilPaid] [datetime] NULL,
[LatestDateForFinalApplication] [datetime] NULL,
[LatestSplittingDate] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[NextMeetingDate] [datetime] NULL,
[NumberOfNewShares] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[PaymentDate] [datetime] NULL,
[Price] [decimal] (23, 10) NULL,
[RecordDate] [datetime] NULL,
[ReverseTakeover] [bit] NULL,
[Status] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[StatusDate] [datetime] NULL,
[TaxAmount] [decimal] (23, 10) NULL,
[TaxDescription] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[TaxRatePercent] [decimal] (23, 10) NULL,
[ExtractSequenceId] [bigint] NOT NULL IDENTITY(1, 1),
[ExtractDate] [datetime] NULL CONSTRAINT [DF__Corporate__Extra__29572725] DEFAULT (getdate()),
[MessageId] [varchar] (256) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CorporateActionStage] ADD CONSTRAINT [PK__Corporat__A1071C3DDEC58D27] PRIMARY KEY CLUSTERED  ([ExtractSequenceId]) ON [PRIMARY]
GO
