IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'STOCK_EXCHANGE\G_DWReportWriter')
CREATE LOGIN [STOCK_EXCHANGE\G_DWReportWriter] FROM WINDOWS
GO
CREATE USER [STOCK_EXCHANGE\G_DWReportWriter] FOR LOGIN [STOCK_EXCHANGE\G_DWReportWriter]
GO
