IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'STOCK_EXCHANGE\BarryM')
CREATE LOGIN [STOCK_EXCHANGE\BarryM] FROM WINDOWS
GO
CREATE USER [STOCK_EXCHANGE\BarryM] FOR LOGIN [STOCK_EXCHANGE\BarryM]
GO
