SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Ian Meade
-- Create date: 13/4/2017
-- Description:	Insert index values into ODS
-- =============================================
CREATE PROCEDURE [dbo].[AddIndexValue]
           @OLAST NUMERIC(8,3),
           @OOPEN NUMERIC(8,3),
           @OHIGH NUMERIC(15,3),
           @OLOW NUMERIC(8,3),
           @ORETURN NUMERIC(8,3),
           @FLAST NUMERIC(8,3),
           @FOPEN NUMERIC(8,3),
           @FHIGH NUMERIC(15,3),
           @FLOW NUMERIC(8,3),
           @FRETURN NUMERIC(8,3),
           @GLAST NUMERIC(8,3),
           @GOPEN NUMERIC(8,3),
           @GHIGH NUMERIC(15,3),
           @GLOW NUMERIC(8,3),
           @GRETURN NUMERIC(8,3),
           @SLAST NUMERIC(8,3),
           @SOPEN NUMERIC(8,3),
           @SHIGH NUMERIC(15,3),
           @SLOW NUMERIC(8,3),
           @SRETURN NUMERIC(8,3),
           @ILAST NUMERIC(8,3),
           @IOPEN NUMERIC(8,3),
           @IHIGH NUMERIC(15,3),
           @ILOW NUMERIC(8,3),
           @IRETURN NUMERIC(8,3),
           @ELAST NUMERIC(8,3),
           @EOPEN NUMERIC(8,3),
           @EHIGH NUMERIC(15,3),
           @ELOW NUMERIC(8,3),
           @ERETURN NUMERIC(8,3),
           @NLAST NUMERIC(8,3),
           @NOPEN NUMERIC(8,3),
           @NHIGH NUMERIC(15,3),
           @NLOW NUMERIC(8,3),
           @XLAST NUMERIC(8,3),
           @XOPEN NUMERIC(8,3),
           @XHIGH NUMERIC(15,3),
           @XLOW NUMERIC(8,3),
           @XRETURN NUMERIC(8,3),
           @VLAST NUMERIC(8,3),
           @VOPEN NUMERIC(8,3),
           @VHIGH NUMERIC(15,3),
           @VLOW NUMERIC(8,3),
           @VRETURN NUMERIC(8,3),
           @LLAST NUMERIC(8,3),
           @LOPEN NUMERIC(8,3),
           @LHIGH NUMERIC(15,3),
           @LLOW NUMERIC(8,3),
           @LRETURN NUMERIC(8,3),
           @CLAST NUMERIC(8,3),
           @COPEN NUMERIC(8,3),
           @CHIGH NUMERIC(15,3),
           @CLOW NUMERIC(8,3),
           @CRETURN NUMERIC(8,3)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	INSERT INTO	
			dbo.IndexValue
		(     
			OLAST,
			OOPEN,
			OHIGH,
			OLOW,
			ORETURN,
			FLAST,
			FOPEN,
			FHIGH,
			FLOW,
			FRETURN,
			GLAST,
			GOPEN,
			GHIGH,
			GLOW,
			GRETURN,
			SLAST,
			SOPEN,
			SHIGH,
			SLOW,
			SRETURN,
			ILAST,
			IOPEN,
			IHIGH,
			ILOW,
			IRETURN,
			ELAST,
			EOPEN,
			EHIGH,
			ELOW,
			ERETURN,
			NLAST,
			NOPEN,
			NHIGH,
			NLOW,
			XLAST,
			XOPEN,
			XHIGH,
			XLOW,
			XRETURN,
			VLAST,
			VOPEN,
			VHIGH,
			VLOW,
			VRETURN,
			LLAST,
			LOPEN,
			LHIGH,
			LLOW,
			LRETURN,
			CLAST,
			COPEN,
			CHIGH,
			CLOW,
			CRETURN
		)
		VALUES
		(
			@OLAST,
			@OOPEN,
			@OHIGH,
			@OLOW,
			@ORETURN,
			@FLAST,
			@FOPEN,
			@FHIGH,
			@FLOW,
			@FRETURN,
			@GLAST,
			@GOPEN,
			@GHIGH,
			@GLOW,
			@GRETURN,
			@SLAST,
			@SOPEN,
			@SHIGH,
			@SLOW,
			@SRETURN,
			@ILAST,
			@IOPEN,
			@IHIGH,
			@ILOW,
			@IRETURN,
			@ELAST,
			@EOPEN,
			@EHIGH,
			@ELOW,
			@ERETURN,
			@NLAST,
			@NOPEN,
			@NHIGH,
			@NLOW,
			@XLAST,
			@XOPEN,
			@XHIGH,
			@XLOW,
			@XRETURN,
			@VLAST,
			@VOPEN,
			@VHIGH,
			@VLOW,
			@VRETURN,
			@LLAST,
			@LOPEN,
			@LHIGH,
			@LLOW,
			@LRETURN,
			@CLAST,
			@COPEN,
			@CHIGH,
			@CLOW,
			@CRETURN
		)

END

GO
