SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- =============================================
-- Author:		Ian Meade
-- Create date: 13/4/2017
-- Description:	Insert index values into ODS
-- =============================================
CREATE PROCEDURE [dbo].[AddIndexValue]
		@v_OVERALL_LAST NUMERIC(8,3),
        @v_OVERALL_OPEN NUMERIC(8,3),
        @v_OVERALL_HIGH NUMERIC(8,3),
        @v_OVERALL_LOW NUMERIC(8,3),
        @v_OVERALL_RETURN NUMERIC(8,3),
        @v_FINANCIAL_LAST NUMERIC(8,3),
        @v_FINANCIAL_OPEN NUMERIC(8,3),
        @v_FINANCIAL_HIGH NUMERIC(8,3),
        @v_FINANCIAL_LOW NUMERIC(8,3),
        @v_FINANCIAL_RETURN NUMERIC(8,3),
        @v_GENERAL_LAST NUMERIC(8,3),
        @v_GENERAL_OPEN NUMERIC(8,3),
        @v_GENERAL_HIGH NUMERIC(8,3),
        @v_GENERAL_LOW NUMERIC(8,3),
        @v_GENERAL_RETURN NUMERIC(8,3),
        @v_SMALL_LAST NUMERIC(8,3),
        @v_SMALL_OPEN NUMERIC(8,3),
        @v_SMALL_HIGH NUMERIC(8,3),
        @v_SMALL_LOW NUMERIC(8,3),
        @v_SMALL_RETURN NUMERIC(8,3),
        @v_ITEQ_LAST NUMERIC(8,3),
        @v_ITEQ_OPEN NUMERIC(8,3),
        @v_ITEQ_HIGH NUMERIC(8,3),
        @v_ITEQ_LOW NUMERIC(8,3),
        @v_ITEQ_RETURN NUMERIC(8,3),
        @v_ETF_LAST NUMERIC(8,3),
        @v_ETF_OPEN NUMERIC(8,3),
        @v_ETF_HIGH NUMERIC(8,3),
        @v_ETF_LOW NUMERIC(8,3),
        @v_ETF_RETURN NUMERIC(8,3),
        @v_INAV_LAST NUMERIC(8,3),
        @v_INAV_OPEN NUMERIC(8,3),
        @v_INAV_HIGH NUMERIC(8,3),
        @v_INAV_LOW NUMERIC(8,3),
        @v_IEX_LAST NUMERIC(8,3),
        @v_IEX_OPEN NUMERIC(8,3),
        @v_IEX_HIGH NUMERIC(8,3),
        @v_IEX_LOW NUMERIC(8,3),
        @v_IEX_RETURN NUMERIC(8,3),
        @v_INVERSE_LAST NUMERIC(8,3),
        @v_INVERSE_OPEN NUMERIC(8,3),
        @v_INVERSE_HIGH NUMERIC(8,3),
        @v_INVERSE_LOW NUMERIC(8,3),
        @v_INVERSE_RETURN NUMERIC(8,3),
        @v_LEVERAGED_LAST NUMERIC(8,3),
        @v_LEVERAGED_OPEN NUMERIC(8,3),
        @v_LEVERAGED_HIGH NUMERIC(8,3),
        @v_LEVERAGED_LOW NUMERIC(8,3),
        @v_LEVERAGED_RETURN NUMERIC(8,3),
        @v_CAPPED_LAST NUMERIC(8,3),
        @v_CAPPED_OPEN NUMERIC(8,3),
        @v_CAPPED_HIGH NUMERIC(8,3),
        @v_CAPPED_LOW NUMERIC(8,3),
        @v_CAPPED_RETURN NUMERIC(8,3)
		   

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	INSERT INTO	
			dbo.IndexValue
		(     
			OLAST,
			OOPEN,
			OHIGH,
			OLOW,
			ORETURN,
			FLAST,
			FOPEN,
			FHIGH,
			FLOW,
			FRETURN,
			GLAST,
			GOPEN,
			GHIGH,
			GLOW,
			GRETURN,
			SLAST,
			SOPEN,
			SHIGH,
			SLOW,
			SRETURN,
			ILAST,
			IOPEN,
			IHIGH,
			ILOW,
			IRETURN,
			ELAST,
			EOPEN,
			EHIGH,
			ELOW,
			ERETURN,
			NLAST,
			NOPEN,
			NHIGH,
			NLOW,
			XLAST,
			XOPEN,
			XHIGH,
			XLOW,
			XRETURN,
			VLAST,
			VOPEN,
			VHIGH,
			VLOW,
			VRETURN,
			LLAST,
			LOPEN,
			LHIGH,
			LLOW,
			LRETURN,
			CLAST,
			COPEN,
			CHIGH,
			CLOW,
			CRETURN
		)
		VALUES
		(
			@v_OVERALL_LAST,
			@v_OVERALL_OPEN,
			@v_OVERALL_HIGH,
			@v_OVERALL_LOW,
			@v_OVERALL_RETURN,
			@v_FINANCIAL_LAST,
			@v_FINANCIAL_OPEN,
			@v_FINANCIAL_HIGH,
			@v_FINANCIAL_LOW,
			@v_FINANCIAL_RETURN,
			@v_GENERAL_LAST,
			@v_GENERAL_OPEN,
			@v_GENERAL_HIGH,
			@v_GENERAL_LOW,
			@v_GENERAL_RETURN,
			@v_SMALL_LAST,
			@v_SMALL_OPEN,
			@v_SMALL_HIGH,
			@v_SMALL_LOW,
			@v_SMALL_RETURN,
			@v_ITEQ_LAST,
			@v_ITEQ_OPEN,
			@v_ITEQ_HIGH,
			@v_ITEQ_LOW,
			@v_ITEQ_RETURN,
			@v_ETF_LAST,
			@v_ETF_OPEN,
			@v_ETF_HIGH,
			@v_ETF_LOW,
			@v_ETF_RETURN,
			@v_INAV_LAST,
			@v_INAV_OPEN,
			@v_INAV_HIGH,
			@v_INAV_LOW,
			@v_IEX_LAST,
			@v_IEX_OPEN,
			@v_IEX_HIGH,
			@v_IEX_LOW,
			@v_IEX_RETURN,
			@v_INVERSE_LAST,
			@v_INVERSE_OPEN,
			@v_INVERSE_HIGH,
			@v_INVERSE_LOW,
			@v_INVERSE_RETURN,
			@v_LEVERAGED_LAST,
			@v_LEVERAGED_OPEN,
			@v_LEVERAGED_HIGH,
			@v_LEVERAGED_LOW,
			@v_LEVERAGED_RETURN,
			@v_CAPPED_LAST,
			@v_CAPPED_OPEN,
			@v_CAPPED_HIGH,
			@v_CAPPED_LOW,
			@v_CAPPED_RETURN
		)

END


GO
