CREATE TABLE [dbo].[XtOdsInstrumentEquityEtfUpdate]
(
[InstrumentGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[InstrumentName] [varchar] (450) COLLATE Latin1_General_CI_AS NULL,
[InstrumentType] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SecurityType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ISIN] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SEDOL] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusDate] [datetime] NULL,
[InstrumentListedDate] [datetime] NULL,
[TradingSysInstrumentName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CompanyGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[MarketName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[WKN] [varchar] (6) COLLATE Latin1_General_CI_AS NULL,
[MNEM] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[InstrumentSedolMasterFileName] [varchar] (40) COLLATE Latin1_General_CI_AS NULL,
[IssuerSedolMasterFileName] [varchar] (300) COLLATE Latin1_General_CI_AS NULL,
[ITEQIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ISEQ20IndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ESMIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[LastEXDivDate] [date] NULL,
[GeneralIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[FinancialIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[OverallIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[SmallCapIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[IssuedDate] [datetime] NULL,
[CurrencyISOCode] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[UnitOfQuotation] [numeric] (23, 10) NULL,
[QuotationCurrencyISOCode] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ISEQ20Freefloat] [numeric] (23, 10) NULL,
[ISEQOverallFreeFloat] [numeric] (23, 10) NULL,
[CFIName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CFICode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[TotalSharesInIssue] [numeric] (28, 6) NULL,
[CompanyListedDate] [datetime] NULL,
[CompanyApprovalDate] [datetime] NULL,
[CompanyApprovalType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CompanyStatusName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Note] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[TransparencyDirectiveYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[MarketAbuseDirectiveYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ProspectusDirectiveYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[PrimaryBusinessSector] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector1] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector2] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector3] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector4] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector5] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[IssuerGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[IssuerName] [varchar] (300) COLLATE Latin1_General_CI_AS NULL,
[IssuerDomicile] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[FinancialYearEndDate] [datetime] NULL,
[IncorporationDate] [datetime] NULL,
[LegalStructure] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AccountingStandard] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[TransparencyDirectiveHomeMemberCountry] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[ProspectusDirectiveHomeMemberCountry] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuerDomicileDomesticYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[FeeCodeName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
