CREATE TABLE [dbo].[DwhDimInstrumentEquityEtf]
(
[InstrumentID] [int] NOT NULL,
[InstrumentGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[InstrumentName] [varchar] (256) COLLATE Latin1_General_CI_AS NULL,
[InstrumentType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[SecurityType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[SEDOL] [varchar] (7) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusID] [smallint] NULL,
[TradingSysInstrumentName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuerName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuerGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[IssuerStatusID] [smallint] NULL,
[CompanyGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CompanyApprovalType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[TransparencyDirectiveYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[MarketAbuseDirectiveYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ProspectusDirectiveYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[MarketID] [smallint] NULL,
[IssuerDomicile] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[WKN] [varchar] (6) COLLATE Latin1_General_CI_AS NULL,
[MNEM] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[PrimaryBusinessSector] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector1] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector2] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector3] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector4] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector5] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[OverallIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[GeneralIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[FinancialIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[SmallCapIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ITEQIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ISEQ20IndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ESMIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[LegalStructure] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AccountingStandard] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[TransparencyDirectiveHomeMemberCountry] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[ProspectusDirectiveHomeMemberCountry] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuerDomicileDomesticYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[FeeCodeName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CurrencyID] [smallint] NULL,
[UnitOfQuotation] [numeric] (19, 9) NULL,
[QuotationCurrencyID] [smallint] NULL,
[ISEQ20Freefloat] [numeric] (19, 6) NULL,
[ISEQOverallFreeFloat] [numeric] (19, 6) NULL,
[IssuerSedolMasterFileName] [varchar] (35) COLLATE Latin1_General_CI_AS NULL,
[InstrumentDomesticYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[CFIName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CFICode] [varchar] (6) COLLATE Latin1_General_CI_AS NULL,
[InstrumentSedolMasterFileName] [varchar] (40) COLLATE Latin1_General_CI_AS NULL,
[TotalSharesInIssue] [numeric] (28, 6) NULL,
[LastEXDivDate] [date] NULL,
[CompanyStatusID] [smallint] NULL,
[CompanyStatusName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Note] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[StartDate] [datetime2] NULL,
[EndDate] [datetime2] NULL,
[CurrentRowYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[BatchID] [int] NULL,
[InstrumentStatusDate] [date] NULL,
[InstrumentListedDate] [date] NULL,
[CompanyApprovalDate] [date] NULL,
[FinancialYearEndDate] [date] NULL,
[IncorporationDate] [date] NULL,
[CompanyListedDate] [date] NULL,
[IssuedDate] [date] NULL,
[InstrumentStatusName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[IssuerStatusName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[MarketName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[MarketCode] [varchar] (15) COLLATE Latin1_General_CI_AS NULL,
[CurrencyISOCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[QuotationCurrencyISOCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DwhDimInstrumentEquityEtf] ADD CONSTRAINT [PK_DwhDimInstrumentEquityEtf] PRIMARY KEY CLUSTERED  ([InstrumentID]) ON [PRIMARY]
GO
