CREATE TABLE [dbo].[XtOdsCompany]
(
[Asset_Type] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[Name] [varchar] (900) COLLATE Latin1_General_CI_AS NULL,
[DelistedDefunct] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[ListingDate] [datetime] NULL,
[ListingStatus] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusDate] [datetime] NULL,
[InstrumentStatusCreatedDatetime] [datetime] NULL,
[Sector] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Subfocus1] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Subfocus2] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Subfocus3] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Subfocus4] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Subfocus5] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ApprovalType] [varchar] (40) COLLATE Latin1_General_CI_AS NULL,
[ApprovalDate] [datetime] NULL,
[TdFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[MadFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PdFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[Gid] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[IssuerGid] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Isin] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[Sedol] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuedDate] [datetime] NULL,
[MarketType] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[SecurityType] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[DenominationCurrency] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[FreeFloatAdj] [numeric] (13, 0) NULL,
[EtfIndexFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[IexiIdexFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[IteqIndexFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[GeneralFinancialFlag] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[SmallCap] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[Note] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[QuotationCurrency] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[UnitOfQuotation] [numeric] (13, 0) NULL,
[Wkn] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Mnem] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[CfiName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CfiCode] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[SmfName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[TotalSharesInIssue] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuedShares] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[InstrumentActualListedDate] [datetime] NULL,
[TradingSysInstrumentName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CompanyGid] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[ExtractSequenceId] [bigint] NULL,
[ExtractDate] [datetime] NULL,
[MessageId] [bigint] NULL
) ON [PRIMARY]
GO
