CREATE TABLE [dbo].[Saft_TxSaft]
(
[FileName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DwhFileID] [int] NULL,
[A_MOD_TIMESTAMP] [datetime2] NULL,
[A_TRADE_LINK_NO] [int] NULL,
[A_SUB_TRANSACTION_NO] [int] NULL,
[A_BUY_SELL_FLAG] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[A_ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[A_TRADE_TYPE] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[A_TRADE_DATE] [datetime2] NULL,
[A_TRADE_TIMESTAMP] [datetime2] NULL,
[A_OTC_TRADE_TIME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[A_PRICE_CURRENCY] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_MATCH_PRICE_X] [decimal] (19, 6) NULL,
[A_TRADE_SIZE_X] [decimal] (19, 6) NULL,
[A_AUCTION_TRADE_FLAG] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[A_MEMBER_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[A_ACCOUNT_TYPE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_ORDER_TYPE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_ORDER_RESTRICTION] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[A_ORDER_MARKET_VALUE] [decimal] (19, 6) NULL,
[A_MEMBER_CTPY_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[A_SETTLEMENT_DATE] [date] NULL,
[A_SETTLEMENT_TYPE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_MOD_REASON_CODE] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_INSERT_TIMESTAMP] [datetime2] NULL,
[A_OTC_TRADE_FLAG_1] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_OTC_TRADE_FLAG_2] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_OTC_TRADE_FLAG_3] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[A_DEFERRED_IND] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[A_IND_PUBLICATION_TIME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[A_TRADER_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[A_BEST_BID_PRICE] [decimal] (19, 6) NULL,
[A_BEST_ASK_PRICE] [decimal] (19, 6) NULL,
[A_OFFICIAL_OPENING_PRICE] [decimal] (19, 6) NULL,
[A_OFFICIAL_CLOSING_PRICE] [decimal] (19, 6) NULL,
[A_TRADE_TIME_OCP] [datetime] NULL
) ON [PRIMARY]
GO
