CREATE TABLE [dbo].[XtOdsCorporateAction]
(
[Gid] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[InstrumentGID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[IssuerGID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CorpActionType] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CorpActionAssetType] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[AdditionalDescription] [varchar] (3000) COLLATE Latin1_General_CI_AS NULL,
[Conditional] [bit] NULL,
[Currency] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Details] [varchar] (3000) COLLATE Latin1_General_CI_AS NULL,
[DividendPerShare] [numeric] (23, 10) NULL,
[DividendRatePercent] [numeric] (23, 10) NULL,
[EffectiveDate] [datetime] NULL,
[ExDate] [datetime] NULL,
[FXRate] [numeric] (23, 10) NULL,
[GrossDividend] [numeric] (23, 10) NULL,
[LatestDateForApplicationNilPaid] [datetime] NULL,
[LatestDateForFinalApplication] [datetime] NULL,
[LatestSplittingDate] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[NextMeetingDate] [datetime] NULL,
[NumberOfNewShares] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[PaymentDate] [datetime] NULL,
[Price] [numeric] (23, 10) NULL,
[RecordDate] [datetime] NULL,
[Status] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[StatusDate] [datetime] NULL,
[TaxAmount] [numeric] (23, 10) NULL,
[TaxDescription] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[TaxRatePercent] [numeric] (23, 10) NULL,
[ExtractSequenceId] [bigint] NULL,
[ExtractDate] [datetime] NULL,
[MessageId] [varchar] (256) COLLATE Latin1_General_CI_AS NULL,
[ExPrice] [numeric] (23, 10) NULL,
[CouponNumber] [numeric] (23, 10) NULL,
[GrossDividendEuro] [numeric] (23, 10) NULL,
[SpecialActionHeadline] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[ReverseTakeover] [bit] NULL
) ON [PRIMARY]
GO
