CREATE TABLE [dbo].[XtOdsCorporateAction]
(
[Gid] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[InstrumentGID] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[IssuerGID] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[CorpActionType] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[CorpActionAssetType] [varchar] (30) COLLATE Latin1_General_CI_AS NOT NULL,
[ActionType] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[AdditionalDescription] [varchar] (3000) COLLATE Latin1_General_CI_AS NULL,
[Conditional] [bit] NULL,
[CouponNumber] [decimal] (23, 10) NULL,
[Currency] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CurrentNumberOfSharesInIssue] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[Details] [varchar] (3000) COLLATE Latin1_General_CI_AS NULL,
[DividendPerShare] [decimal] (23, 10) NULL,
[DividendRatePercent] [decimal] (23, 10) NULL,
[EffectiveDate] [datetime] NULL,
[ExDate] [datetime] NULL,
[ExPrice] [decimal] (23, 10) NULL,
[FXRate] [decimal] (23, 10) NULL,
[GrossDividendEuro] [decimal] (23, 10) NULL,
[GrossDividend] [decimal] (23, 10) NULL,
[LatestDateForApplicationNilPaid] [datetime] NULL,
[LatestDateForFinalApplication] [datetime] NULL,
[LatestSplittingDate] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[NextMeetingDate] [datetime] NULL,
[NumberOfNewShares] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[PaymentDate] [datetime] NULL,
[Price] [decimal] (23, 10) NULL,
[RecordDate] [datetime] NULL,
[ReverseTakover] [bit] NULL,
[RightsPrice] [decimal] (23, 10) NULL,
[SharePrice] [decimal] (23, 10) NULL,
[Status] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[StatusDate] [datetime] NULL,
[TaxAmount] [decimal] (23, 10) NULL,
[TaxDescription] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[TaxRatePercent] [decimal] (23, 10) NULL,
[Unconditional] [bit] NULL,
[ExtractSequenceId] [bigint] NOT NULL,
[ExtractDate] [datetime] NULL CONSTRAINT [DF__XtOdsCorp__Extra__6CD828CA] DEFAULT (getdate()),
[MessageId] [varchar] (256) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
