CREATE TABLE [dbo].[XtOdsInstrumentEquityEtfUpdate]
(
[InstrumentGlobalID] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[InstrumentName] [varchar] (900) COLLATE Latin1_General_CI_AS NULL,
[InstrumentType] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[SecurityType] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[ISIN] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[SEDOL] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusName] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusDate] [datetime] NULL,
[TradingSysInstrumentName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CompanyGlobalID] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[MarketName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[WKN] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[MNEM] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[GeneralIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[InstrumentListedDate] [date] NULL,
[InstrumentSedolMasterFileName] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[ISEQ20IndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[IssuerSedolMasterFileName] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[ITEQIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[LastEXDivDateID] [varchar] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[OverallIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[SecurityQualifier] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[FinancialIndexYN] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[SmallCapIndexYN] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[IssuedDate] [datetime] NULL,
[CurrencyISOCode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[UnitOfQuotation] [numeric] (22, 9) NULL,
[QuotationCurrencyISOCode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[ISEQ20Freefloat] [numeric] (19, 6) NULL,
[ISEQOverallFreeFloat] [float] NULL,
[CFIName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CFICode] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[TotalSharesInIssue] [numeric] (28, 6) NULL,
[CompanyListedDate] [datetime] NULL,
[CompanyApprovalDate] [datetime] NULL,
[CompanyApprovalType] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[CompanyStatusName] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Note] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[TransparencyDirectiveYN] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[MarketAbuseDirectiveYN] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[ProspectusDirectiveYN] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PrimaryBusinessSector] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector1] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector2] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector3] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector4] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SubBusinessSector5] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[IssuerGlobalID] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[IssuerName] [varchar] (600) COLLATE Latin1_General_CI_AS NULL,
[IssuerDomicile] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[FinancialYearEndDate] [datetime] NULL,
[IncorporationDate] [datetime] NULL,
[LegalStructure] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AccountingStandard] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[TransparencyDirectiveHomeMemberCountry] [varchar] (400) COLLATE Latin1_General_CI_AS NULL,
[ProspectusDirectiveHomeMemberCountry] [varchar] (200) COLLATE Latin1_General_CI_AS NULL,
[IssuerDomicileDomesticYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[FeeCodeName] [varchar] (200) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
