CREATE TABLE [ETL].[FactEtfSnapshotMerge]
(
[ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[InstrumentID] [int] NOT NULL,
[CurrentInstrumentID] [int] NOT NULL,
[InstrumentStatusID] [smallint] NULL,
[DateID] [int] NOT NULL,
[LastExDivDateID] [int] NULL,
[OCPDateID] [int] NULL,
[OCPTimeID] [smallint] NULL,
[OCPTime] [time] NULL,
[UtcOCPTime] [time] NULL,
[LTPDateID] [int] NULL,
[LTPTimeID] [smallint] NULL,
[LTPTime] [time] NULL,
[UtcLTPTime] [time] NULL,
[MarketID] [smallint] NULL,
[TotalSharesInIssue] [numeric] (28, 6) NULL,
[IssuedSharesToday] [numeric] (28, 6) NULL,
[ExDivYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[OpenPrice] [numeric] (19, 6) NULL,
[LowPrice] [numeric] (19, 6) NULL,
[HighPrice] [numeric] (19, 6) NULL,
[BidPrice] [numeric] (19, 6) NULL,
[OfferPrice] [numeric] (19, 6) NULL,
[ClosingAuctionBidPrice] [numeric] (19, 6) NULL,
[ClosingAuctionOfferPrice] [numeric] (19, 6) NULL,
[OCP] [numeric] (19, 6) NULL,
[LTP] [numeric] (19, 6) NULL,
[MarketCap] [numeric] (28, 6) NULL,
[MarketCapEur] [numeric] (28, 6) NULL,
[Turnover] [numeric] (19, 6) NULL,
[TurnoverND] [numeric] (19, 6) NULL,
[TurnoverEur] [numeric] (19, 6) NULL,
[TurnoverNDEur] [numeric] (19, 6) NULL,
[TurnoverOB] [numeric] (19, 6) NULL,
[TurnoverOBEur] [numeric] (19, 6) NULL,
[Volume] [bigint] NULL,
[VolumeND] [bigint] NULL,
[VolumeOB] [bigint] NULL,
[Deals] [int] NULL,
[DealsOB] [int] NULL,
[DealsND] [int] NULL,
[ISEQ20Shares] [numeric] (28, 6) NULL,
[ISEQ20Price] [numeric] (19, 6) NULL,
[ISEQ20Weighting] [numeric] (9, 6) NULL,
[ISEQ20MarketCap] [numeric] (28, 6) NULL,
[ISEQOverallWeighting] [numeric] (9, 6) NULL,
[ISEQOverallMarketCap] [numeric] (28, 6) NULL,
[ISEQOverallBeta30] [numeric] (19, 6) NULL,
[ISEQOverallBeta250] [numeric] (19, 6) NULL,
[ISEQOverallPrice] [numeric] (19, 6) NULL,
[ISEQOverallShares] [numeric] (28, 6) NULL,
[OverallIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[GeneralIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[FinancialIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[SmallCapIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ITEQIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ISEQ20IndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ESMIndexYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExCapYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExEntitlementYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExRightsYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExSpecialYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[BatchID] [int] NULL,
[XYZ] [nchar] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
