CREATE TABLE [ETL].[FactEtfSnapshotMerge]
(
[InstrumentID] [int] NULL,
[ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[InstrumentType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CurrencyID] [smallint] NULL,
[SourceTable] [varchar] (6) COLLATE Latin1_General_CI_AS NULL,
[AggregationDate] [date] NULL,
[AggregationDateID] [int] NULL,
[InstrumentGlobalID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[OCP] [numeric] (19, 6) NULL,
[OCPDateID] [int] NULL,
[OCPTime] [time] NULL,
[OCPTimeID] [int] NULL,
[OpenPrice] [numeric] (19, 6) NULL,
[UtcOCPTime] [time] NULL,
[LastPrice] [numeric] (19, 6) NULL,
[LTPDateID] [int] NULL,
[LTPTimeID] [smallint] NULL,
[LTPTime] [time] NULL,
[UtcLTPTime] [time] NULL,
[LowPrice] [numeric] (19, 6) NULL,
[HighPrice] [numeric] (19, 6) NULL,
[Deals] [int] NULL,
[DealsOB] [int] NULL,
[DealsND] [int] NULL,
[Volume] [int] NULL,
[VolumeOB] [int] NULL,
[VolumeND] [int] NULL,
[Turnover] [numeric] (38, 6) NULL,
[TurnoverOB] [numeric] (38, 6) NULL,
[TurnoverND] [numeric] (38, 6) NULL,
[TurnoverEur] [numeric] (38, 11) NULL,
[TurnoverObEur] [numeric] (38, 19) NULL,
[TurnoverNdEur] [numeric] (38, 19) NULL,
[BidPrice] [numeric] (19, 6) NULL,
[OfferPrice] [numeric] (19, 6) NULL,
[ClosingAuctionBidPrice] [numeric] (19, 6) NULL,
[ClosingAuctionOfferPrice] [numeric] (19, 6) NULL,
[TotalSharesInIssue] [numeric] (28, 6) NULL,
[ExchangeRate] [numeric] (19, 6) NULL,
[MarketCap] [numeric] (38, 6) NULL,
[MarketCapEur] [numeric] (38, 6) NULL,
[BatchID] [int] NULL,
[MarketID] [smallint] NULL,
[ISEQ20Freefloat] [numeric] (19, 6) NULL,
[ISEQ20IndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ISEQOverallFreeFloat] [numeric] (19, 6) NULL,
[OverallIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[GeneralIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[FinancialIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[SmallCapIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ITEQIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ESMIndexYN] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[PrimaryMarket] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[InstrumentStatusID] [smallint] NULL,
[LastEXDivDate] [date] NULL,
[LtpDateTime] [datetime2] NULL,
[OcpDateTime] [datetime] NULL,
[LastExDivDateID] [int] NULL,
[ExDivYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExCapYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExEntitlementYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExRightsYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[ExSpecialYN] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[NAVCalcDateID] [int] NULL,
[NAV] [numeric] (19, 6) NULL
) ON [PRIMARY]
GO
