CREATE TABLE [Report].[RawTcC810]
(
[T7_ODS_FileListRawTcFileID] [int] NOT NULL,
[RawTc810Id] [int] NOT NULL,
[REPORT_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[REPORT_EFF_DATE] [date] NULL,
[REPORT_PROCESS_DATE] [date] NULL,
[ENV_ONE] [tinyint] NULL,
[ENV_TWO] [tinyint] NULL,
[CLRMEM_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CLRMEM_SETTLE_LOC] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CLRMEM_SETTLE_ACC] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[EXCHMEMB_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[OWNER_EXMEMB_INST_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[OWNER_EXMEMB_BR_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[INSTRU_ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[UNITS] [tinyint] NULL,
[TRANS_TIME] [bigint] NULL,
[PARTA_SUBGRP_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[PARTA_USR_NO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[UNIQ_TRADE_NO] [int] NULL,
[TRADE_NO_SUFX] [tinyint] NULL,
[TRANS_TYPE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ORIGIN_TYPE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CROSS_IND] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[SETTLE_IND] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[OTC_TRADE_TIME] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ORDER_INSTR_ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[ORD_NO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[EXECUTOR_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[INTERMEM_ORD_NO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[FREE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ACC_TYPE_CODE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ACC_TYPE_NO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[BUY_SELL_IND] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[NETTING_TYPE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[MATCHED_QTY] [decimal] (28, 10) NULL,
[MATCHED_PRICE] [decimal] (28, 10) NULL,
[SETTLE_AMOUNT] [decimal] (28, 10) NULL,
[SETTLE_DATE] [date] NULL,
[SETTLE_CODE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ACCRUED_INTEREST] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[ACCRUED_INTEREST_DAY] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[EXCHMEM_INST_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[EXCHMEM_BR_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[PART_USR_GRP_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[PART_USR_NO] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[COUNTER_EXCHMEM_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[COUNTER_EXCHMEM_BR_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[COUNTER_CRL_SET_MEM_ID] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[COUNTER_SETL_LOC] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[COUNTER_SETL_ACC] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[COUNTER_KASSEN_NO] [int] NULL,
[DEPOSITORY_TYPE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[TRANS_FEE] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[TRANS_FEE_CURRENCY] [varchar] (30) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [Report].[RawTcC810] ADD CONSTRAINT [PK_RawTcC810] PRIMARY KEY CLUSTERED  ([T7_ODS_FileListRawTcFileID], [RawTc810Id]) ON [PRIMARY]
GO
