CREATE TABLE [dbo].[TxSaft]
(
[TxSfaftID] [bigint] NOT NULL IDENTITY(1, 1),
[DwhFileID] [int] NOT NULL,
[A_MOD_TIMESTAMP] [datetime2] NOT NULL,
[A_MOD_TIMESTAMP_GMT] [datetimeoffset] NULL,
[A_TRADE_LINK_NO] [int] NOT NULL,
[A_SUB_TRANSACTION_NO] [int] NOT NULL,
[A_BUY_SELL_FLAG] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[A_ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NOT NULL,
[A_TRADE_TYPE] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[A_TRADE_DATE] [datetime2] NOT NULL,
[A_TRADE_TIMESTAMP] [datetime2] NOT NULL,
[A_TRADE_TIMESTAMP_GMT] [datetimeoffset] NULL,
[A_OTC_TRADE_TIME] [time] NOT NULL,
[A_PRICE_CURRENCY] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_MATCH_PRICE_X] [decimal] (19, 6) NOT NULL,
[A_TRADE_SIZE_X] [decimal] (19, 6) NOT NULL,
[A_AUCTION_TRADE_FLAG] [varchar] (2) COLLATE Latin1_General_CI_AS NOT NULL,
[A_MEMBER_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[A_ACCOUNT_TYPE] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_ORDER_TYPE] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_ORDER_RESTRICTION] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[A_ORDER_MARKET_VALUE] [decimal] (19, 6) NOT NULL,
[A_MEMBER_CTPY_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[A_SETTLEMENT_DATE] [date] NOT NULL,
[A_SETTLEMENT_TYPE] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_MOD_REASON_CODE] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_INSERT_TIMESTAMP] [datetime2] NOT NULL,
[A_OTC_TRADE_FLAG_1] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_OTC_TRADE_FLAG_2] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_OTC_TRADE_FLAG_3] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[A_DEFERRED_IND] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[A_IND_PUBLICATION_TIME] [datetime2] NULL,
[A_IND_PUBLICATION_TIME_GMT] [datetimeoffset] NULL,
[A_TRADER_ID] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[A_BEST_BID_PRICE] [decimal] (19, 6) NOT NULL,
[A_BEST_ASK_PRICE] [decimal] (19, 6) NOT NULL,
[A_OFFICIAL_OPENING_PRICE] [decimal] (19, 6) NOT NULL,
[A_OFFICIAL_CLOSING_PRICE] [decimal] (19, 6) NOT NULL,
[A_TRADE_TIME_OCP] [datetime] NOT NULL,
[A_TRADE_TIME_OCP_GMT] [datetimeoffset] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TxSaft] ADD CONSTRAINT [PK_TxSaft] PRIMARY KEY CLUSTERED  ([TxSfaftID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TxSaft_1] ON [dbo].[TxSaft] ([DwhFileID], [A_ISIN], [A_TRADE_TIME_OCP], [A_OFFICIAL_CLOSING_PRICE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TxSaft] ON [dbo].[TxSaft] ([DwhFileID], [A_TRADE_DATE], [A_SUB_TRANSACTION_NO], [A_BUY_SELL_FLAG], [A_MOD_REASON_CODE]) ON [PRIMARY]
GO
