CREATE TABLE [dbo].[RawTc810_NEW]
(
[RawTc810_NEW_ID] [int] NOT NULL IDENTITY(1, 1),
[FileID] [int] NOT NULL,
[exchNam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[envText] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[rptCod] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[rptNam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[rptFlexKey] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[membId] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[membLglNam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[rptPrntEffDat] [datetime] NULL,
[rptPrntEffTim] [datetime] NULL,
[rptPrntRunDat] [datetime] NULL,
[participant] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[partLngName] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[membClgIdCod] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[membCcpClgIdCod] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[settlAcct] [int] NULL,
[settlLocat] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[settlCurr] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[sumMembTotBuyOrdr] [bigint] NULL,
[sumMembTotSellOrdr] [bigint] NULL,
[businessUnit] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[busUntLngName] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[businessUnitId] [int] NULL,
[sumPartTotBuyOrdr] [bigint] NULL,
[sumPartTotSellOrdr] [bigint] NULL,
[user] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[product] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[instrumentType] [tinyint] NULL,
[instrumentId] [bigint] NULL,
[instrumentMnemonic] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[isinCod] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[wknNo] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[instNam] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[time18] [datetime] NULL,
[tradeType] [tinyint] NULL,
[matchEvent] [int] NULL,
[matchStep] [int] NULL,
[matchDeal] [int] NULL,
[parentDeal] [tinyint] NULL,
[dealItem] [int] NULL,
[tradeNumber] [int] NULL,
[exchangeOrderId] [numeric] (20, 0) NULL,
[versionNo] [smallint] NULL,
[acctTypGrp] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[buyCod] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ordrPrtFilCod] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[execQty] [bigint] NULL,
[execPrc] [numeric] (28, 10) NULL,
[ordrTyp] [tinyint] NULL,
[limOrdrPrc] [numeric] (28, 10) NULL,
[timeValidity] [tinyint] NULL,
[tradingRestriction] [tinyint] NULL,
[settlAmnt] [numeric] (28, 10) NULL,
[settlDat] [datetime] NULL,
[ctrPtyId] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[userOrdrNum] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[text] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[kindOfDepo] [tinyint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RawTc810_NEW] ADD CONSTRAINT [PK_RawTc810_NEW] PRIMARY KEY CLUSTERED  ([FileID], [RawTc810_NEW_ID]) ON [PRIMARY]
GO
