CREATE TABLE [dbo].[PriceFile]
(
[PriceFileID] [bigint] NOT NULL IDENTITY(1, 1),
[FileID] [int] NOT NULL,
[ISIN] [varchar] (12) COLLATE Latin1_General_CI_AS NOT NULL,
[CURRENCY] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[PRICE_TIMESTAMP] [datetime2] NOT NULL,
[MOD_TIMESTAMP] [datetime2] NULL,
[PRICE_DATE] [date] NULL,
[BEST_BID_PRICE] [numeric] (19, 6) NULL,
[BEST_ASK_PRICE] [numeric] (19, 6) NULL,
[CLOSING_AUCT_BID_PRICE] [numeric] (19, 6) NULL,
[CLOSING_AUCT_ASK_PRICE] [numeric] (19, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PriceFile] ADD CONSTRAINT [PK_PriceFile] PRIMARY KEY CLUSTERED  ([PriceFileID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PriceFile] ON [dbo].[PriceFile] ([ISIN], [PRICE_DATE], [PRICE_TIMESTAMP]) ON [PRIMARY]
GO
