CREATE SCHEMA [DWH]
AUTHORIZATION [dbo]
GO
GRANT CONTROL ON SCHEMA:: [DWH] TO [EtlRunner]
GO
GRANT SELECT ON SCHEMA:: [DWH] TO [ReportRunner]
GO
GRANT EXECUTE ON SCHEMA:: [DWH] TO [ReportRunner]
GO
GRANT SELECT ON SCHEMA:: [DWH] TO [ReportWriter]
GO
GRANT EXECUTE ON SCHEMA:: [DWH] TO [ReportWriter]
GO
